["server"]
environment="DEVELOPMENT"
port="4000"
timezone="Europe/Berlin"
powered_by_header="server"

["mail"]
host="smtp.test.com"
port=24
secure=false
user="user"
pass="pass"
to="to@to.com"

["log"]
log_dir="log"
log_file="app.log"
max_size_in_mb=1
max_backups=3
max_age=28
color=false