name: Build latest

on:
  push: 
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        ref: main

    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.ACTOR }}
        password: ${{ secrets.REGISTRY_TOKEN }}
      
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ secrets.REGISTRY_NAME }}/${{ secrets.IMAGE }}:latest